openapi: 3.0.0
info:
  title: Микросервис Поддержки Коворкинга
  version: 1.0.0
  description: API для обработки жалоб, запросов и взаимодействия со службой поддержки
servers:
  - url: 'https://coworking-api.example.com/support  '

# 🔐 Аутентификация и разграничение прав
security:
  - BearerAuth: []

components:
  # 🔑 Схемы безопасности
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
    RoleCheck:
      type: apiKey
      in: header
      name: X-User-Role

  # 📦 Схемы данных 
  schemas:
    Ticket:
      type: object
      properties:
        id:
          type: integer
          description: Уникальный идентификатор тикета
        userId:
          type: integer
          description: Идентификатор пользователя
        categoryId:
          type: integer
          description: Идентификатор категории
        title:
          type: string
          description: Заголовок тикета
        description:
          type: string
          description: Описание проблемы
        status:
          type: string
          description: Статус тикета ('ожидает', 'в процессе', 'закрыт')
        attachments:
          type: array
          items:
            type: string
          description: Список приложенных файлов
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time
    CreateTicketRequest:
      type: object
      properties:
        userId:
          type: integer
        categoryId:
          type: integer
        title:
          type: string
        description:
          type: string
        attachments:
          type: array
          items:
            type: string
      required: [userId, categoryId, title, description]
    UpdateTicketStatusRequest:
      type: object
      properties:
        status:
          type: string
    Comment:
      type: object
      properties:
        id:
          type: integer
        ticketId:
          type: integer
        authorId:
          type: integer
        text:
          type: string
        createdAt:
          type: string
          format: date-time
    AddCommentRequest:
      type: object
      properties:
        authorId:
          type: integer
        text:
          type: string
      required: [authorId, text]
    Category:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        description:
          type: string
    CreateCategoryRequest:
      type: object
      properties:
        name:
          type: string
        description:
          type: string
      required: [name]
    SupportReport:
      type: object
      properties:
        period:
          type: object
          properties:
            startDate:
              type: string
              format: date
            endDate:
              type: string
              format: date
        totalTickets:
          type: integer
        resolvedTickets:
          type: integer
        averageResolutionTime:
          type: string
        categoryDistribution:
          type: object
          additionalProperties:
            type: integer
    GenerateSupportReportRequest:
      type: object
      properties:
        startDate:
          type: string
          format: date
        endDate:
          type: string
          format: date
      required: [startDate, endDate]

# 🚦 Разграничение прав по эндпоинтам
paths:
  /tickets:
    get:
      summary: Получение списка тикетов
      security:
        - BearerAuth: []
      tags:
        - Поддержка
      parameters:
        - name: userId
          in: query
          description: Фильтр по идентификатору пользователя
          schema:
            type: integer
        - name: status
          in: query
          description: Фильтр по статусу тикета
          schema:
            type: string
      responses:
        '200':
          description: Успешный ответ
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Ticket'
        '401':
          description: Unauthorized
        '500':
          description: Internal Server Error
    post:
      summary: Создание нового тикета
      security:
        - BearerAuth: []
      tags:
        - Поддержка
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateTicketRequest'
      responses:
        '201':
          description: Тикет успешно создан
          headers:
            Location:
              description: URI нового ресурса
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Ticket'
        '400':
          description: Неверные данные в запросе
        '401':
          description: Unauthorized
        '500':
          description: Internal Server Error

  /tickets/{ticketId}:
    get:
      summary: Получение информации о тикете
      security:
        - BearerAuth: []
      tags:
        - Поддержка
      parameters:
        - name: ticketId
          in: path
          description: Идентификатор тикета
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Успешный ответ
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Ticket'
        '401':
          description: Unauthorized
        '404':
          description: Тикет не найден
        '500':
          description: Internal Server Error
    put:
      summary: Обновление статуса тикета
      security:
        - BearerAuth: []
        - RoleCheck: [ADMIN]
      tags:
        - Поддержка
      parameters:
        - name: ticketId
          in: path
          description: Идентификатор тикета
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateTicketStatusRequest'
      responses:
        '200':
          description: Статус тикета успешно обновлён
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Ticket'
        '400':
          description: Неверные данные в запросе
        '401':
          description: Unauthorized
        '403':
          description: Недостаточно прав
        '404':
          description: Тикет не найден
        '500':
          description: Internal Server Error
    delete:
      summary: Удаление тикета
      security:
        - BearerAuth: []
        - RoleCheck: [ADMIN]
      tags:
        - Поддержка
      parameters:
        - name: ticketId
          in: path
          description: Идентификатор тикета
          required: true
          schema:
            type: integer
      responses:
        '204':
          description: Тикет успешно удалён
        '401':
          description: Unauthorized
        '403':
          description: Недостаточно прав
        '404':
          description: Тикет не найден
        '500':
          description: Internal Server Error

  /tickets/{ticketId}/comments:
    post:
      summary: Добавление комментария к тикету
      security:
        - BearerAuth: []
      tags:
        - Комментарии
      parameters:
        - name: ticketId
          in: path
          description: Идентификатор тикета
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AddCommentRequest'
      responses:
        '201':
          description: Комментарий успешно добавлен
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Comment'
        '400':
          description: Неверные данные в запросе
        '401':
          description: Unauthorized
        '403':
          description: Недостаточно прав
        '404':
          description: Тикет не найден
        '500':
          description: Internal Server Error

  /categories:
    get:
      summary: Получение списка категорий
      security:
        - BearerAuth: []
      tags:
        - Категории
      responses:
        '200':
          description: Успешный ответ
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Category'
        '401':
          description: Unauthorized
        '500':
          description: Internal Server Error
    post:
      summary: Создание новой категории
      security:
        - BearerAuth: []
        - RoleCheck: [ADMIN]
      tags:
        - Категории
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateCategoryRequest'
      responses:
        '201':
          description: Категория успешно создана
          headers:
            Location:
              description: URI нового ресурса
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Category'
        '400':
          description: Неверные данные в запросе
        '401':
          description: Unauthorized
        '403':
          description: Недостаточно прав
        '500':
          description: Internal Server Error

  /reports:
    post:
      summary: Генерация отчета по тикетам
      security:
        - BearerAuth: []
        - RoleCheck: [ADMIN]
      tags:
        - Отчеты
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/GenerateSupportReportRequest'
      responses:
        '200':
          description: Отчет успешно сгенерирован
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SupportReport'
        '400':
          description: Неверные данные в запросе
        '401':
          description: Unauthorized
        '403':
          description: Недостаточно прав
        '500':
          description: Internal Server Error